package com.fauv.analyzer.message;

public class DMOMessage {

	public static final String HEADER_START_DATE_FIELD = "START_DATE_CANNOT_BE_NULL";
	public static final String HEADER_START_TIME_FIELD = "START_TIME_CANNOT_BE_NULL";
	public static final String HEADER_END_DATE_FIELD = "END_DATE_CANNOT_BE_NULL";
	public static final String HEADER_END_TIME_FIELD = "END_TIME_CANNOT_BE_NULL";
	public static final String HEADER_PART_NUMBER_FIELD = "PART_NUMBER_CANNOT_BE_NULL_OR_EMPTY";
	public static final String HEADER_EQUIPMENT_NAME_FIELD = "PART_NUMBER_CANNOT_BE_NULL_OR_EMPTY";
	public static final String HEADER_SAMPLE_ID_FIELD = "SAMPLE_ID_CANNOT_BE_NULL_OR_EMPTY";
	public static final String HEADER_INSPECTOR_FIELD = "INSPECTOR_CANNOT_BE_NULL_OR_EMPTY";
	
	public static final String AXIS_COORDINATE_NAME = "AXIS_COORDINATE_NAME_CANNOT_BE_NULL_OR_EMPTY";
	public static final String AXIS_COORDINATE_LOWER_TOLERANCE = "AXIS_COORDINATE_LOWER_TOLERANCE_CANNOT_BE_NULL";
	public static final String AXIS_COORDINATE_SUPERIOR_TOLERANCE = "AXIS_COORDINATE_SUPERIOR_TOLERANCE_CANNOT_BE_NULL";
	public static final String AXIS_COORDINATE_AXIS = "AXIS_COORDINATE_AXIS_CANNOT_BE_NULL";		

	public static final String PMP_NAME = "PMP_NAME_CANNOT_BE_NULL_OR_EMPTY";
	
}
