package com.fauv.analyzer.message;

public class ModelMessage {

	public static final String FORM_ID = "ID_CANNOT_BE_NULL";
	public static final String FORM_PART_NUMBER = "PART_NUMBER_CANNOT_BE_NULL_OR_EMPTLY";
	public static final String FORM_PART_NUMBER_SIZE = "PART_NUMBER_MUST_HAVE_BETWEEN_1_AND_255_CHARACTERS";
	public static final String FORM_STEP_DESCRIPTION = "STEP_DESCRIPTION_CANNOT_BE_NULL_OR_EMPTLY";
	public static final String FORM_STEP_DESCRIPTION_SIZE = "STEP_DESCRIPTION_MUST_HAVE_BETWEEN_1_AND_255_CHARACTERS";
	public static final String FORM_CAR = "CAR_CANNOT_BE_NULL";
	
	public static final String NOT_FOUND = "MODEL_NOT_FOUND";
	
	public static final String NOMINAL_PMP_NAME = "NOMINAL_PMP_NAME_CANNOT_BE_NULL_OR_EMPTLY";
	public static final String NOMINAL_PMP_AXIS = "NOMINAL_PMP_AXIS_CANNOT_BE_NULL";
	public static final String NOMINAL_PMP_X = "NOMINAL_PMP_AXIS_X_CANNOT_BE_NULL";
	public static final String NOMINAL_PMP_Y = "NOMINAL_PMP_AXIS_Y_CANNOT_BE_NULL";
	public static final String NOMINAL_PMP_Z = "NOMINAL_PMP_AXIS_Z_BE_NULL";
	public static final String NOMINAL_PMP_AXIS_COORDINATE_LIST = "NOMINAL_PMP_AXIS_COORDINATE_LIST_CANNOT_BE_NULL_OR_EMPTLY";
	
	public static final String NOMINAL_AXIS_COORDINATE_NAME = "NOMINAL_AXIS_COORDINATE_NAME_CANNOT_BE_NULL_OR_EMPTLY";
	public static final String NOMINAL_AXIS_COORDINATE_LOWER_TOLERANCE = "NOMINAL_AXIS_COORDINATE_LOWER_TOLERANCE_CANNOT_BE_NULL";
	public static final String NOMINAL_AXIS_COORDINATE_HIGHER_TOLERANCE = "NOMINAL_AXIS_COORDINATE_HIGHER_TOLERANCE_CANNOT_BE_NULL";
	public static final String NOMINAL_AXIS_COORDINATE_AXIS = "NOMINAL_AXIS_COORDINATE_AXIS_CANNOT_BE_NULL";
	public static final String NOMINAL_AXIS_COORDINATE_NOT_FIND_BY_NAME_IN_UPDATE = "NOMINAL_AXIS_COORDINATE_NOT_FIND_BY_NAME_IN_UPDATE";
	public static final String THIS_NOMINAL_AXIS_COORDINATE_CANNOT_HAS_ID_NULL = "THIS_NOMINAL_AXIS_COORDINATE_CANNOT_HAS_ID_NULL";
		
	public static final String NOMINAL_FM_NAME = "NOMINAL_FM_NAME_CANNOT_BE_NULL_OR_EMPTLY";
	public static final String NOMINAL_FM_AXIS = "NOMINAL_FM_AXIS_CANNOT_BE_NULL";
	public static final String NOMINAL_FM_HIGHER_VALUE_TOLERANCE = "NOMINAL_FM_HIGHER_TOLERANCE_CANNOT_BE_NULL";
	public static final String NOMINAL_FM_LOWER_VALUE_TOLERANCE = "NOMINAL_FM_LOWER_TOLERANCE_CANNOT_BE_NULL";
	public static final String NOMINAL_FM_DEFAULT_VALUE = "NOMINAL_FM_DEFAULT_VALUE_CANNOT_BE_NULL";
	public static final String NOMINAL_FM_CATALOG = "NOMINAL_FM_CATALOG_CANNOT_BE_NULL";
	public static final String NOMINAL_FM_LEVEL = "NOMINAL_FM_LEVEL_CANNOT_BE_NULL";
	public static final String NOMINAL_FM_NOMINAL_POINTS = "NOMINAL_FM_POINTS_TO_MAP_CANNOT_BE_NULL_OR_EMPTLY";
	
}
