package com.fauv.analyzer.message;

public class SampleMessage {

	public static final String UPLOAD_DATE = "UPLOAD_DATE_CANNOT_BE_NULL";
	public static final String UPLOAD_USER = "UPLOAD_USER_CANNOT_BE_NULL_OR_EMPTLY";
	public static final String UPLOAD_USER_SIZE = "UPLOAD_USER_MUST_HAVE_BETWEEN_1_AND_45_CHARACTERS";
	public static final String MODEL = "MODEL_CANNOT_BE_NULL";
	public static final String EQUIPMENT = "EQUIPMENT_CANNOT_BE_NULL";
	public static final String PIN = "PIN_CANNOT_BE_NULL_OR_EMPTLY";
	public static final String PIN_SIZE = "PIN_MUST_HAVE_BETWEEN_1_AND_10_CHARACTERS";
	public static final String SCAN_INIT_DATE = "SCAN_INIT_DATE_CANNOT_BE_NULL";
	public static final String SCAN_END_DATE = "SCAN_END_DATE_CANNOT_BE_NULL";
	public static final String STATUS = "STATUS_CANNOT_BE_NULL";
	
	public static final String NOT_FOUND = "SAMPLE_NOT_FOUND";
	public static final String DUPLICATE = "DUPLICATE_SAMPLE_FOR_THIS_MODEL";
	public static final String PMP_NOT_FOUND = "PMP_NOT_FOUND";
	public static final String FM_NOT_FOUND = "FM_NOT_FOUND";
	public static final String AXIS_COORDINATE_NOT_FOUND = "AXIS_COORDINATE_NOT_FOUND";
	
	public static final String MEASUREMENT_PMP_X = "MEASUREMENT_PMP_AXIS_X_CANNOT_BE_NULL";
	public static final String MEASUREMENT_PMP_Y = "MEASUREMENT_PMP_AXIS_Y_CANNOT_BE_NULL";
	public static final String MEASUREMENT_PMP_Z = "MEASUREMENT_PMP_AXIS_Z_CANNOT_BE_NULL";
	public static final String MEASUREMENT_PMP_ASSOCIATION = "MEASUREMENT_PMP_ASSOCIATION_CANNOT_BE_NULL";
	public static final String MEASUREMENT_PMP_AXIS_COORDINATE_LIST = "MEASUREMENT_PMP_AXIS_COORDINATE_LIST_CANNOT_BE_NULL_OR_EMPTLY";
	
	public static final String MEASUREMENT_AXIS_COORDINATE_ASSOCIATION = "MEASUREMENT_AXIS_COORDINATE_ASSOCIATION_CANNOT_BE_NULL";
	public static final String MEASUREMENT_AXIS_COORDINATE_VALUE = "MEASUREMENT_AXIS_COORDINATE_VALUE_CANNOT_BE_NULL";
	public static final String MEASUREMENT_AXIS_COORDINATE_TOLARANCE= "MEASUREMENT_AXIS_COORDINATE_TOLERANCE_CANNOT_BE_NULL";
	
	public static final String MEASUREMENT_FM_VALUE = "MEASUREMENT_FM_VALUE_CANNOT_BE_NULL";
	public static final String MEASUREMENT_FM_TOLERANCE = "MEASUREMENT_FM_TOLERANCE_CANNOT_BE_NULL";
	public static final String MEASUREMENT_FM_ASSOCIATION = "MEASUREMENTL_FM_ASSOCIATION_CANNOT_BE_NULL";
}
