package com.fauv.analyzer.enums;

public enum StatisticCriteria {
	POINT_ABOVE_LCS, 
	POINT_BELOW_LCS, 
	FIFTEEN_CONSECUTIVE_POINS_IN_ZONE_C, 
	FOURTEEN_CONSECUTIVE_POINTS_ALTERNATING_UP_AND_DOWN,
	EIGHT_CONSECURTIVE_POINTS_OUT_OF_ZONE_A,
	TWO_OUT_OF_THREE_CONSECUTIVE_POINTS_IN_ZONE_A,
	FOUR_OUT_OF_FIVE_CONSECUTIVE_POINTS_OUTSIDE_ZONE_C,
	NINE_CONSECUTIVE_POINTS_ON_THE_SAME_SIDE_OF_THE_MIDDLE_LINE,
	OUT_OF_TOLERANCE;
}
